# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sudosai/programs/tiny/Sort

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sudosai/programs/tiny/Sort

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sudosai/programs/tiny/Sort/CMakeFiles /home/sudosai/programs/tiny/Sort/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sudosai/programs/tiny/Sort/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sort

# Build rule for target.
Sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sort
.PHONY : Sort

# fast build rule for target.
Sort/fast:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/build
.PHONY : Sort/fast

graph-utils/menu.o: graph-utils/menu.c.o

.PHONY : graph-utils/menu.o

# target to build an object file
graph-utils/menu.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/menu.c.o
.PHONY : graph-utils/menu.c.o

graph-utils/menu.i: graph-utils/menu.c.i

.PHONY : graph-utils/menu.i

# target to preprocess a source file
graph-utils/menu.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/menu.c.i
.PHONY : graph-utils/menu.c.i

graph-utils/menu.s: graph-utils/menu.c.s

.PHONY : graph-utils/menu.s

# target to generate assembly for a file
graph-utils/menu.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/menu.c.s
.PHONY : graph-utils/menu.c.s

graph-utils/response.o: graph-utils/response.c.o

.PHONY : graph-utils/response.o

# target to build an object file
graph-utils/response.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/response.c.o
.PHONY : graph-utils/response.c.o

graph-utils/response.i: graph-utils/response.c.i

.PHONY : graph-utils/response.i

# target to preprocess a source file
graph-utils/response.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/response.c.i
.PHONY : graph-utils/response.c.i

graph-utils/response.s: graph-utils/response.c.s

.PHONY : graph-utils/response.s

# target to generate assembly for a file
graph-utils/response.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/response.c.s
.PHONY : graph-utils/response.c.s

graph-utils/status.o: graph-utils/status.c.o

.PHONY : graph-utils/status.o

# target to build an object file
graph-utils/status.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/status.c.o
.PHONY : graph-utils/status.c.o

graph-utils/status.i: graph-utils/status.c.i

.PHONY : graph-utils/status.i

# target to preprocess a source file
graph-utils/status.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/status.c.i
.PHONY : graph-utils/status.c.i

graph-utils/status.s: graph-utils/status.c.s

.PHONY : graph-utils/status.s

# target to generate assembly for a file
graph-utils/status.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/graph-utils/status.c.s
.PHONY : graph-utils/status.c.s

helper/swap.o: helper/swap.c.o

.PHONY : helper/swap.o

# target to build an object file
helper/swap.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/helper/swap.c.o
.PHONY : helper/swap.c.o

helper/swap.i: helper/swap.c.i

.PHONY : helper/swap.i

# target to preprocess a source file
helper/swap.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/helper/swap.c.i
.PHONY : helper/swap.c.i

helper/swap.s: helper/swap.c.s

.PHONY : helper/swap.s

# target to generate assembly for a file
helper/swap.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/helper/swap.c.s
.PHONY : helper/swap.c.s

main/Main.o: main/Main.c.o

.PHONY : main/Main.o

# target to build an object file
main/Main.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/main/Main.c.o
.PHONY : main/Main.c.o

main/Main.i: main/Main.c.i

.PHONY : main/Main.i

# target to preprocess a source file
main/Main.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/main/Main.c.i
.PHONY : main/Main.c.i

main/Main.s: main/Main.c.s

.PHONY : main/Main.s

# target to generate assembly for a file
main/Main.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/main/Main.c.s
.PHONY : main/Main.c.s

src/BubbleSort.o: src/BubbleSort.c.o

.PHONY : src/BubbleSort.o

# target to build an object file
src/BubbleSort.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/BubbleSort.c.o
.PHONY : src/BubbleSort.c.o

src/BubbleSort.i: src/BubbleSort.c.i

.PHONY : src/BubbleSort.i

# target to preprocess a source file
src/BubbleSort.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/BubbleSort.c.i
.PHONY : src/BubbleSort.c.i

src/BubbleSort.s: src/BubbleSort.c.s

.PHONY : src/BubbleSort.s

# target to generate assembly for a file
src/BubbleSort.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/BubbleSort.c.s
.PHONY : src/BubbleSort.c.s

src/InsertionSort.o: src/InsertionSort.c.o

.PHONY : src/InsertionSort.o

# target to build an object file
src/InsertionSort.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/InsertionSort.c.o
.PHONY : src/InsertionSort.c.o

src/InsertionSort.i: src/InsertionSort.c.i

.PHONY : src/InsertionSort.i

# target to preprocess a source file
src/InsertionSort.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/InsertionSort.c.i
.PHONY : src/InsertionSort.c.i

src/InsertionSort.s: src/InsertionSort.c.s

.PHONY : src/InsertionSort.s

# target to generate assembly for a file
src/InsertionSort.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/InsertionSort.c.s
.PHONY : src/InsertionSort.c.s

src/MergeSort.o: src/MergeSort.c.o

.PHONY : src/MergeSort.o

# target to build an object file
src/MergeSort.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/MergeSort.c.o
.PHONY : src/MergeSort.c.o

src/MergeSort.i: src/MergeSort.c.i

.PHONY : src/MergeSort.i

# target to preprocess a source file
src/MergeSort.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/MergeSort.c.i
.PHONY : src/MergeSort.c.i

src/MergeSort.s: src/MergeSort.c.s

.PHONY : src/MergeSort.s

# target to generate assembly for a file
src/MergeSort.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/MergeSort.c.s
.PHONY : src/MergeSort.c.s

src/QuickSort.o: src/QuickSort.c.o

.PHONY : src/QuickSort.o

# target to build an object file
src/QuickSort.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/QuickSort.c.o
.PHONY : src/QuickSort.c.o

src/QuickSort.i: src/QuickSort.c.i

.PHONY : src/QuickSort.i

# target to preprocess a source file
src/QuickSort.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/QuickSort.c.i
.PHONY : src/QuickSort.c.i

src/QuickSort.s: src/QuickSort.c.s

.PHONY : src/QuickSort.s

# target to generate assembly for a file
src/QuickSort.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/QuickSort.c.s
.PHONY : src/QuickSort.c.s

src/SelectionSort.o: src/SelectionSort.c.o

.PHONY : src/SelectionSort.o

# target to build an object file
src/SelectionSort.c.o:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/SelectionSort.c.o
.PHONY : src/SelectionSort.c.o

src/SelectionSort.i: src/SelectionSort.c.i

.PHONY : src/SelectionSort.i

# target to preprocess a source file
src/SelectionSort.c.i:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/SelectionSort.c.i
.PHONY : src/SelectionSort.c.i

src/SelectionSort.s: src/SelectionSort.c.s

.PHONY : src/SelectionSort.s

# target to generate assembly for a file
src/SelectionSort.c.s:
	$(MAKE) -f CMakeFiles/Sort.dir/build.make CMakeFiles/Sort.dir/src/SelectionSort.c.s
.PHONY : src/SelectionSort.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Sort"
	@echo "... edit_cache"
	@echo "... graph-utils/menu.o"
	@echo "... graph-utils/menu.i"
	@echo "... graph-utils/menu.s"
	@echo "... graph-utils/response.o"
	@echo "... graph-utils/response.i"
	@echo "... graph-utils/response.s"
	@echo "... graph-utils/status.o"
	@echo "... graph-utils/status.i"
	@echo "... graph-utils/status.s"
	@echo "... helper/swap.o"
	@echo "... helper/swap.i"
	@echo "... helper/swap.s"
	@echo "... main/Main.o"
	@echo "... main/Main.i"
	@echo "... main/Main.s"
	@echo "... src/BubbleSort.o"
	@echo "... src/BubbleSort.i"
	@echo "... src/BubbleSort.s"
	@echo "... src/InsertionSort.o"
	@echo "... src/InsertionSort.i"
	@echo "... src/InsertionSort.s"
	@echo "... src/MergeSort.o"
	@echo "... src/MergeSort.i"
	@echo "... src/MergeSort.s"
	@echo "... src/QuickSort.o"
	@echo "... src/QuickSort.i"
	@echo "... src/QuickSort.s"
	@echo "... src/SelectionSort.o"
	@echo "... src/SelectionSort.i"
	@echo "... src/SelectionSort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

